name: golden_sneaker_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  provider: ^6.0.5

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.ico"
  web:
    generate: true
    image_path: "assets/images/favicon.ico"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/favicon.ico"
    icon_size: 48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Rubik-Light
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf

    - family: Rubik-SemiBold
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf  

    - family: Rubik-Bold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf




